name: Claude Code Action
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    # akiyoshi-yusuke のみが @claude を使用可能
    if: |
      (github.actor == 'akiyoshi-yusuke') &&
      (contains(github.event.comment.body, '@claude') || 
       contains(github.event.issue.body, '@claude') || 
       contains(github.event.pull_request.body, '@claude') || 
       contains(github.event.review.body, '@claude'))
    runs-on: ubuntu-latest
    steps:
      - name: Claude Code Action Official
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}